[tools]
actionlint = "1.7.10"
hadolint = "2.14.0"
python = "3.14.2"
ruff = "0.14.14"
ty = "0.0.11"
uv = "0.9.26"
zizmor = "1.20.0"
"aqua:suzuki-shunsuke/ghalint" = "1.5.4"
"aqua:suzuki-shunsuke/pinact" = "3.8.0"
