[tools]
actionlint = "1.7.10"
hadolint = "2.14.0"
python = "3.14.2"
ruff = "0.14.14"
uv = "0.9.28"
"aqua:suzuki-shunsuke/ghalint" = "1.5.5"
"aqua:suzuki-shunsuke/pinact" = "3.9.0"
"aqua:zizmorcore/zizmor" = "1.22.0"
"ubi:astral-sh/ty" = "0.0.14"
