[tools]
actionlint = "1.7.11"
hadolint = "2.14.0"
python = "3.14.3"
ruff = "0.15.1"
uv = "0.10.4"
"aqua:suzuki-shunsuke/ghalint" = "1.5.5"
"aqua:suzuki-shunsuke/pinact" = "3.9.0"
"aqua:zizmorcore/zizmor" = "1.22.0"
"ubi:astral-sh/ty" = "0.0.17"
